version: 2.1

orbs:
  node: circleci/node@4.1
  cypress: cypress-io/cypress@3.3.1

jobs:
  build: # skipping based on workflow
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - run:
          name: Add dependencies
          command: npm ci
      - run:
          name: Start Application
          command: npm run start
      - run:
          name: Run Cypress Tests
          command: npx cypress run --browser chrome

  deploy:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://git.heroku.com/fe-habit-at.git

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          start-command: 'npm run start'
      #- build
      - deploy:
          requires:
            - cypress/run

          filters:
            branches:
              only: main
