version: 2.1

orbs:
  node: circleci/node@4.1
  cypress: cypress-io/cypress@3.1.1

jobs:
  build:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - run:
          name: Add dependencies
          command: npm ci
      - run:
          name: Start Application
          command: npm start
      - run:
          name: Run Cypress Tests
          command: npx cypress run --headless

  deploy:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy to Heroku
          command: |
            echo "Deploying to Heroku..."
            git remote add heroku https://git.heroku.com/fe-habit-at.git
            git push heroku main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
