version: 2.1

orbs:
  node: circleci/node@4.1
  cypress: cypress-io/cypress@3.3.1

jobs:
  deploy:
    docker:
      - image: cypress/browsers:latest
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy Main to Heroku
          command: |
            echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" > ~/.netrc
            echo "machine git.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
            chmod 600 ~/.netrc
            git remote add heroku https://git.heroku.com/fe-habit-at.git
            git push heroku main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
          start-command: 'npm run start'
      #- build
      - deploy:
          requires:
            - cypress/run

          filters:
            branches:
              only: main
