version: 2.1

orbs:
  node: circleci/node@4.1
  cypress: cypress-io/cypress@3.1.1

jobs:
  build:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Install additional dependencies
          command: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Run Cypress Tests
          command: npx cypress run --headless

  deploy:
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Deploy to Heroku
          command: |
            echo "Deploying to Heroku..."
            git remote add heroku https://git.heroku.com/fe-habit-at.git
            git push heroku main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
